### ISSUE TITLE
侧边栏样式

### ISSUE THREAD

**Issue by snakeUni** [front-swordsman/snake-design#13]
problem：目前侧边栏太靠中间导致内容区太小，对于PC端操作区域太小会导致页面太长。并且会随着右边内容滚动条的滚动而滚动
![image](https://user-images.githubusercontent.com/17973020/55601587-263fc300-5794-11e9-95f7-c8d67471c9c7.png)
expected: 侧边栏靠左边，不随着右边滚动条的滚动而滚动，如果随着滚动期望是`sticky`的形式，滚动的固定像素就不滚动了。类似于`antd`或者`Taro`都可以。
![image](https://user-images.githubusercontent.com/17973020/55601624-63a45080-5794-11e9-9c54-c903b04a7ed8.png)

**Comment by MuYunyun** [comment]
stick 的后续可以加上, 另外左侧的宽度后续也可考虑自适应(等 row 布局先弄好)。
